
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

enum PartnerId
{
    PARTNER_NONE,
    PARTNER_STEVEN,
    PARTNER_COUNT,
};

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
