#ifndef GUARD_CONSTANTS_FIELD_SPECIALS_H
#define GUARD_CONSTANTS_FIELD_SPECIALS_H

enum ScrollMulti
{
    SCROLL_MULTI_BADGES,
    SCROLL_MULTI_SILPHCO_FLOORS,
    SCROLL_MULTI_BERRY_POWDER,
    SCROLL_MULTI_BF_RECEPTIONIST,
    SCROLL_MULTI_BF_MOVE_TUTOR_1,
    SCROLL_MULTI_BF_MOVE_TUTOR_2,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_1,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_2,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_VITAMIN_VENDOR,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_HOLD_ITEM_VENDOR,
    SCROLL_MULTI_NONE = 99,
};

#define MAX_SCROLL_MULTI_ON_SCREEN 6
#define MAX_SCROLL_MULTI_LENGTH 16

#endif // GUARD_CONSTANTS_FIELD_SPECIALS_H
