#ifndef GUARD_CONSTANTS_MENU_H
#define GUARD_CONSTANTS_MENU_H

// Std String Ids
enum StdStringID
{
    STDSTRING_BOULDER_BADGE,
    STDSTRING_CASCADE_BADGE,
    STDSTRING_THUNDER_BADGE,
    STDSTRING_RAINBOW_BADGE,
    STDSTRING_SOUL_BADGE,
    STDSTRING_MARSH_BADGE,
    STDSTRING_VOLCANO_BADGE,
    STDSTRING_EARTH_BADGE,
    STDSTRING_COINS,
    STDSTRING_ITEMS_POCKET,
    STDSTRING_KEY_ITEMS_POCKET,
    STDSTRING_POKEBALLS_POCKET,
    STDSTRING_TM_CASE,
    STDSTRING_BERRY_POUCH,
    STDSTRING_SINGLE,
    STDSTRING_DOUBLE,
    STDSTRING_MULTI,
    STDSTRING_MULTI_LINK,
    STDSTRING_BATTLE_DOME,
    STDSTRING_BATTLE_FACTORY,
    STDSTRING_BATTLE_PALACE,
    STDSTRING_BATTLE_ARENA,
    STDSTRING_BATTLE_PIKE,
    STDSTRING_BATTLE_PYRAMID,
};

#endif //GUARD_CONSTANTS_MENU_H
